### ISSUE TITLE
Unhandled Error Caught 2

### ISSUE THREAD

**Issue by ZeroDot1** [pfbrowning/ng-radio#5]
An error occurs when loading the online version of NG Radio.

```js
An Error Has Occurred

Unhandled Error Caught

Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'radio-browser' ZYCi/me</t.prototype.noMatchError@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:820151 ZYCi/me</t.prototype.apply/<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:819804 9Z1F/c</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:77551 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 xMyE/c</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1505708 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 MGBS/i</e.prototype.notifyError@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:575637 rPjj/i</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1389133 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 FFOo/l</e.prototype._error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556 FFOo/l</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250 9Z1F/c</e.prototype.error@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:77614 xMyE/c</e.prototype._complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1505831 FFOo/l</e.prototype.complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372334 FFOo/l</e.prototype._complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372635 FFOo/l</e.prototype.complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372334 FFOo/l</e.prototype._complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372635 FFOo/l</e.prototype.complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372334 psW0/d</e.prototype._complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1380246 FFOo/l</e.prototype.complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372334 FFOo/l</e.prototype._complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372635 FFOo/l</e.prototype.complete@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372334 r/<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:4498 6blF/l</t.prototype._trySubscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54387 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54173 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 psW0/l</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1379487 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 VnD//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:719603 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 t9fZ/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1426047 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 xMyE/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1505033 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 9Z1F/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:77309 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 f/<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:375145 o@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1560659 psW0/d</e.prototype._innerSub@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1380118 psW0/d</e.prototype._tryNext@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1379993 psW0/d</e.prototype._next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1379816 FFOo/l</e.prototype.next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372170 i/e<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:666637 6blF/l</t.prototype._trySubscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54387 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54173 psW0/l</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1379487 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 AxiF/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:87306 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 xMyE/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1505033 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 9Z1F/u</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:77309 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 67Y//s</t.prototype.call@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:49660 6blF/l</t.prototype.subscribe@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:54051 f/<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:375145 o@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1560659 15JJ/d</e.prototype._innerSub@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:17576 15JJ/d</e.prototype._next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:17380 FFOo/l</e.prototype.next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372170 15JJ/d</e.prototype.notifyNext@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:17990 rPjj/i</e.prototype._next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1389025 FFOo/l</e.prototype.next@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372170 i/</<@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:686079 0TWp/</</c</e.prototype.invoke@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:7104 onInvoke@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:246405 0TWp/</</c</e.prototype.invoke@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:7044 0TWp/</</i</t.prototype.run@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:2307 I/<@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:13771 0TWp/</</c</e.prototype.invokeTask@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:7788 onInvokeTask@http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:246317 0TWp/</</c</e.prototype.invokeTask@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:7709 0TWp/</</i</t.prototype.runTask@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:2970 g@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:10055 0TWp/</</l</t.invokeTask@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:8900 m@http://radio.browninglogic.com/polyfills.3aa7b014fa67a15c9b3a.js:1:22317 k@http://radio.browninglogic.com/polyfills.3aa7b014fa67a1
```5c9b3a.js:1:22620

**Comment by ZeroDot1** [comment]
Hmmmm, when I open it with the Chromebrowser the error is a little different.

```js
An Error Has Occurred
Unhandled Error Caught

Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'radio-browser' Error: Cannot match any routes. URL Segment: 'radio-browser' at t.noMatchError (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:820151) at e.selector (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:819804) at e.error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:77551) at e._error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556) at e.error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250) at e._error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556) at e.error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250) at e._error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372556) at e.error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:372250) at e._error (http://radio.browninglogic.com/main.d596a87b8906e9ca5cac.js:1:1505708)
```

**Comment by pfbrowning** [comment]
That's strange.  It works fine on my end and I can't reproduce the error that you're getting.  The error message suggests that you might have an old version of the app cached.

Could you try refreshing with Ctrl + F5 to see if that helps?  If not, could you try explicitly completely clearing your cache?  If it continues to happen after that, could you give detailed reproduction steps?

**Comment by ZeroDot1** [comment]
Hi @pfbrowning,
Thanks for your answer, I just found the problem while testing.
The error only occurs if you visit the online version via the following link: http://radio.browninglogic.com/radio-browser

**Comment by pfbrowning** [comment]
That's no longer a valid route.  Do you see that link posted somewhere?  The correct route for radio-browser is now http://radio.browninglogic.com/app/radio-browser

**Comment by ZeroDot1** [comment]
Thank you very much for your answers.

OK, I changed my bookmarks and backup to the new link.
I'm closing this here because the problem is solved.
